### ISSUE TITLE
Polishing Session class

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#23]
### Description

- [x] Do we need another name for Session f.e. `vManageSession()` #33 
- [x] port as an `Optional` parameter (#28 )
- [x] auth parameter, new authorization way #26 
- [x] swapping urllib for requests #33 
- [x] `__repr__()` (#37 )
- [x] unittests

**Comment by tehAgitto** [comment]
Covered by #240
